### ISSUE TITLE
Too slow to encode AAC

### ISSUE THREAD

**Issue by kskshaf** [AmusementClub/OKEGui#14]
Personally, I think it is too slow to encode the AAC as the default process: _Lossless Audio > eac3to > FLAC > QAAC > AAC_. And if I used the video with FLAC tracks, FLAC will be encode by _eac3to-libFLAC_ unnecessary(>_<).  Extract _Lossless Audio_(such as FLAC、PCM) files directly for QAAC to encode AAC maybe the fastest way.

中文说明：我个人觉得按照默认流程编码 AAC 太慢了。而且如果我用带有 FLAC 音轨的视频来压制，FLAC 还会再被 _eac3to-libFLAC_ 不必要地编码一遍(>_<)。直接抽取无损音轨（如 FLAC、PCM）给 QAAC 去编码 AAC 或许是最快的方式。

**Comment by AkarinVS** [comment]
are you sure qaac encoding pcm input is *significantly* faster than encoding flac inputs? (Any measurements?)
flac files are much smaller than pcm files, so if there aren't significant benefits, I'd prefer to keep the current process as is.

**Comment by tautcony** [comment]
> We should forget about small efficiencies, say about 97% of the time: premature optimization is the root of all evil.
> <div align="right">—— Donald E. Knuth</div>

**Comment by AkarinVS** [comment]
It's more of a balancing issue.
getting rid of the unnecessary flac conversion would definitely be faster, but the issue is whether its speed benefits can outweigh the increased disk consumption (and code complexity.)

qaac encoding is indeed slow, but the following video encoding is generally much much slower, so it probably doesn't matter much for batch encodings.

**Comment by kskshaf** [comment]
Okay, it might be the best way now.

**Comment by kskshaf** [comment]
@tautcony Yes, it's right.
